import { DM_Sans,Lora } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Header from "@/components/Header";
import { Toaster } from "sonner";
const lora=Lora({
  subsets: ["latin"],
  style: ["normal","italic"],
  variable: "--font-serif",
  weight: ["400", "500"],
});
const dmSans=DM_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500" ,"600"],
})


export const metadata = {
  title: "Prept",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      theme:dark
    }}>

    <html
      lang="en" suppressHydrationWarning
      >
      <body className={ `${lora.variable} ${dmSans.variable} font-sans` }>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            >
              {/* {header} */}
              <Header/>
        <main className="min-h-screen">

        {children}
        </main>
        <Toaster richColors position="top-right" />
        <footer className="relative z-10 border-t border-white/7 py-12  mx-auto px-6 flex flex-wrap items-center justify-center text-stone-400">
              Made with ❤️ by Sameer
            </footer>
          </ThemeProvider>
        </body>
    </html>
            </ClerkProvider>
  );
}
